os: linux
language: python
python:
  - "2.7"

services:
  - mongodb

install:
  # Required to install Shinken
  - sudo apt-get update && sudo apt-get install -y python-pip libgnutls28-dev libssl-dev
  - ./test/setup_test.sh

script:
  # Unit tests
  - cur_dir=$PWD
  - echo "Current directory '$cur_dir' ..."
  - export PYTHONPATH=$PYTHONPATH:$PWD
  - export PYTHONPATH=$PYTHONPATH:$PWD/test/tmp/shinken # we also need shinken test/modules...
  - export PYTHONPATH=$PYTHONPATH:$PWD/test/tmp/shinken/test # we also need shinken test/modules...
  - echo "Python path '$PYTHONPATH' ..."
  - cd test/tmp/shinken/test
  - pytest -vv --durations=0 --no-print-logs --cov="$cur_dir"/module --cov-report=xml --cov-config "$cur_dir"/test/.coveragerc "$cur_dir"/test/test_*.py

  # Static code analysis
  - cd "$cur_dir"
  # -- pycodestyle (former pep8)
  - pycodestyle --max-line-length=120 --ignore=E402,W503 --exclude='*.pyc' module
  # -- pylint
  - pylint --rcfile=.pylintrc -r no module

after_success:
  - bash <(curl -s https://codecov.io/bash) -f test/tmp/shinken/test/coverage.xml
